### ISSUE TITLE
Add installation and setup details. Update Readme

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/Priority-Msg-Bot#3]
Add all the important things in the readme:
- [ ] Add installation instructions
- [ ] Add Execution instructions
- [ ] Add Screenshot of the bot
- [ ] Add the stack details and workflow of the bot

**Comment by ramaneswaran** [comment]
Okay will get it done by today

**Comment by Geek-ubaid** [comment]
Issue resolved in [PR](#4 )
